package shop

import (
	"github.com/pixel-plaza-dev/uru-databases-2-protobuf-common/types/grpc"
)

// Interceptions is the list of gRPC methods to intercept
var Interceptions = map[grpc.Method]grpc.Interception{
	UpdateAdminRevision:                grpc.AccessToken,
	GetAdminRevisions:                  grpc.AccessToken,
	CloseAdminRevision:                 grpc.AccessToken,
	AddBusiness:                        grpc.AccessToken,
	GetBusiness:                        grpc.None,
	UpdateBusiness:                     grpc.AccessToken,
	SetBusinessProfilePicture:          grpc.AccessToken,
	OpenAdminRevisionToBusiness:        grpc.AccessToken,
	DeleteBusiness:                     grpc.AccessToken,
	AddBusinessOwner:                   grpc.AccessToken,
	RemoveBusinessOwner:                grpc.AccessToken,
	GetBusinessOwners:                  grpc.AccessToken,
	AddBusinessClient:                  grpc.AccessToken,
	IsBusinessClient:                   grpc.AccessToken,
	AddMarketCategory:                  grpc.AccessToken,
	GetMarketCategory:                  grpc.None,
	UpdateMarketCategory:               grpc.AccessToken,
	AddBusinessMarketCategory:          grpc.AccessToken,
	GetBusinessMarketCategories:        grpc.None,
	AddStore:                           grpc.AccessToken,
	GetStore:                           grpc.None,
	DeleteStore:                        grpc.AccessToken,
	GetUnoccupiedStores:                grpc.None,
	AddBranch:                          grpc.AccessToken,
	GetBranch:                          grpc.None,
	GetBusinessBranches:                grpc.None,
	UpdateBranch:                       grpc.AccessToken,
	CloseTemporarilyBranch:             grpc.AccessToken,
	OpenBranch:                         grpc.AccessToken,
	OpenAdminRevisionToBranch:          grpc.AccessToken,
	DeleteBranch:                       grpc.AccessToken,
	AddBranchRent:                      grpc.AccessToken,
	GetBranchRents:                     grpc.AccessToken,
	UpdateBranchRent:                   grpc.AccessToken,
	GetUnpaidBranchRents:               grpc.AccessToken,
	GetBusinessUnpaidBranchRents:       grpc.AccessToken,
	AddProductCategory:                 grpc.AccessToken,
	GetProductCategory:                 grpc.None,
	UpdateProductCategory:              grpc.AccessToken,
	AddProduct:                         grpc.AccessToken,
	GetProduct:                         grpc.None,
	UpdateProduct:                      grpc.AccessToken,
	SearchProducts:                     grpc.None,
	OpenAdminRevisionToProduct:         grpc.AccessToken,
	AddBusinessProduct:                 grpc.AccessToken,
	GetBusinessProduct:                 grpc.None,
	UpdateBusinessProduct:              grpc.AccessToken,
	SearchBusinessProducts:             grpc.None,
	OpenAdminRevisionToBusinessProduct: grpc.AccessToken,
	AddBranchProduct:                   grpc.AccessToken,
	GetBranchProduct:                   grpc.None,
	SearchBranchProducts:               grpc.None,
	UpdateBranchProduct:                grpc.AccessToken,
}
