// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/pixel_plaza/business.proto

package business

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Business_AddBusiness_FullMethodName                  = "/pixel_plaza.Business/AddBusiness"
	Business_GetBusiness_FullMethodName                  = "/pixel_plaza.Business/GetBusiness"
	Business_UpdateBusiness_FullMethodName               = "/pixel_plaza.Business/UpdateBusiness"
	Business_SetBusinessProfilePicture_FullMethodName    = "/pixel_plaza.Business/SetBusinessProfilePicture"
	Business_SuspendBusiness_FullMethodName              = "/pixel_plaza.Business/SuspendBusiness"
	Business_ActivateBusiness_FullMethodName             = "/pixel_plaza.Business/ActivateBusiness"
	Business_DeleteBusiness_FullMethodName               = "/pixel_plaza.Business/DeleteBusiness"
	Business_AddBusinessOwner_FullMethodName             = "/pixel_plaza.Business/AddBusinessOwner"
	Business_RemoveBusinessOwner_FullMethodName          = "/pixel_plaza.Business/RemoveBusinessOwner"
	Business_GetBusinessOwners_FullMethodName            = "/pixel_plaza.Business/GetBusinessOwners"
	Business_AddBusinessClient_FullMethodName            = "/pixel_plaza.Business/AddBusinessClient"
	Business_IsBusinessClient_FullMethodName             = "/pixel_plaza.Business/IsBusinessClient"
	Business_AddMarketCategory_FullMethodName            = "/pixel_plaza.Business/AddMarketCategory"
	Business_GetMarketCategory_FullMethodName            = "/pixel_plaza.Business/GetMarketCategory"
	Business_UpdateMarketCategory_FullMethodName         = "/pixel_plaza.Business/UpdateMarketCategory"
	Business_AddBusinessMarketCategory_FullMethodName    = "/pixel_plaza.Business/AddBusinessMarketCategory"
	Business_GetBusinessMarketCategories_FullMethodName  = "/pixel_plaza.Business/GetBusinessMarketCategories"
	Business_AddStore_FullMethodName                     = "/pixel_plaza.Business/AddStore"
	Business_GetStore_FullMethodName                     = "/pixel_plaza.Business/GetStore"
	Business_DeleteStore_FullMethodName                  = "/pixel_plaza.Business/DeleteStore"
	Business_GetUnoccupiedStores_FullMethodName          = "/pixel_plaza.Business/GetUnoccupiedStores"
	Business_AddBranch_FullMethodName                    = "/pixel_plaza.Business/AddBranch"
	Business_GetBranch_FullMethodName                    = "/pixel_plaza.Business/GetBranch"
	Business_GetBusinessBranches_FullMethodName          = "/pixel_plaza.Business/GetBusinessBranches"
	Business_UpdateBranch_FullMethodName                 = "/pixel_plaza.Business/UpdateBranch"
	Business_SuspendBranch_FullMethodName                = "/pixel_plaza.Business/SuspendBranch"
	Business_ActivateBranch_FullMethodName               = "/pixel_plaza.Business/ActivateBranch"
	Business_DeleteBranch_FullMethodName                 = "/pixel_plaza.Business/DeleteBranch"
	Business_AddStoreBranchRent_FullMethodName           = "/pixel_plaza.Business/AddStoreBranchRent"
	Business_GetStoreBranchRents_FullMethodName          = "/pixel_plaza.Business/GetStoreBranchRents"
	Business_UpdateStoreBranchRent_FullMethodName        = "/pixel_plaza.Business/UpdateStoreBranchRent"
	Business_GetUnpaidBranchRents_FullMethodName         = "/pixel_plaza.Business/GetUnpaidBranchRents"
	Business_GetBusinessUnpaidBranchRents_FullMethodName = "/pixel_plaza.Business/GetBusinessUnpaidBranchRents"
	Business_AddProductCategory_FullMethodName           = "/pixel_plaza.Business/AddProductCategory"
	Business_GetProductCategory_FullMethodName           = "/pixel_plaza.Business/GetProductCategory"
	Business_UpdateProductCategory_FullMethodName        = "/pixel_plaza.Business/UpdateProductCategory"
	Business_AddProduct_FullMethodName                   = "/pixel_plaza.Business/AddProduct"
	Business_GetProduct_FullMethodName                   = "/pixel_plaza.Business/GetProduct"
	Business_UpdateProduct_FullMethodName                = "/pixel_plaza.Business/UpdateProduct"
	Business_SearchProducts_FullMethodName               = "/pixel_plaza.Business/SearchProducts"
	Business_SuspendProduct_FullMethodName               = "/pixel_plaza.Business/SuspendProduct"
	Business_ActivateProduct_FullMethodName              = "/pixel_plaza.Business/ActivateProduct"
	Business_AddBusinessProduct_FullMethodName           = "/pixel_plaza.Business/AddBusinessProduct"
	Business_GetBusinessProduct_FullMethodName           = "/pixel_plaza.Business/GetBusinessProduct"
	Business_UpdateBusinessProduct_FullMethodName        = "/pixel_plaza.Business/UpdateBusinessProduct"
	Business_SearchBusinessProducts_FullMethodName       = "/pixel_plaza.Business/SearchBusinessProducts"
	Business_SuspendBusinessProduct_FullMethodName       = "/pixel_plaza.Business/SuspendBusinessProduct"
	Business_ActivateBusinessProduct_FullMethodName      = "/pixel_plaza.Business/ActivateBusinessProduct"
	Business_AddBranchProduct_FullMethodName             = "/pixel_plaza.Business/AddBranchProduct"
	Business_GetBranchProduct_FullMethodName             = "/pixel_plaza.Business/GetBranchProduct"
	Business_SearchBranchProducts_FullMethodName         = "/pixel_plaza.Business/SearchBranchProducts"
	Business_UpdateBranchProduct_FullMethodName          = "/pixel_plaza.Business/UpdateBranchProduct"
)

// BusinessClient is the client API for Business service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BusinessClient interface {
	AddBusiness(ctx context.Context, in *AddBusinessRequest, opts ...grpc.CallOption) (*AddBusinessResponse, error)
	GetBusiness(ctx context.Context, in *GetBusinessRequest, opts ...grpc.CallOption) (*GetBusinessResponse, error)
	UpdateBusiness(ctx context.Context, in *UpdateBusinessRequest, opts ...grpc.CallOption) (*UpdateBusinessResponse, error)
	SetBusinessProfilePicture(ctx context.Context, in *SetBusinessProfilePictureRequest, opts ...grpc.CallOption) (*SetBusinessProfilePictureResponse, error)
	SuspendBusiness(ctx context.Context, in *SuspendBusinessRequest, opts ...grpc.CallOption) (*SuspendBusinessResponse, error)
	ActivateBusiness(ctx context.Context, in *ActivateBusinessRequest, opts ...grpc.CallOption) (*ActivateBusinessResponse, error)
	DeleteBusiness(ctx context.Context, in *DeleteBusinessRequest, opts ...grpc.CallOption) (*DeleteBusinessResponse, error)
	AddBusinessOwner(ctx context.Context, in *AddBusinessOwnerRequest, opts ...grpc.CallOption) (*AddBusinessOwnerResponse, error)
	RemoveBusinessOwner(ctx context.Context, in *RemoveBusinessOwnerRequest, opts ...grpc.CallOption) (*RemoveBusinessOwnerResponse, error)
	GetBusinessOwners(ctx context.Context, in *GetBusinessOwnersRequest, opts ...grpc.CallOption) (*GetBusinessOwnersResponse, error)
	AddBusinessClient(ctx context.Context, in *AddBusinessClientRequest, opts ...grpc.CallOption) (*AddBusinessClientResponse, error)
	IsBusinessClient(ctx context.Context, in *IsBusinessClientRequest, opts ...grpc.CallOption) (*IsBusinessClientResponse, error)
	AddMarketCategory(ctx context.Context, in *AddMarketCategoryRequest, opts ...grpc.CallOption) (*AddMarketCategoryResponse, error)
	GetMarketCategory(ctx context.Context, in *GetMarketCategoryRequest, opts ...grpc.CallOption) (*GetMarketCategoryResponse, error)
	UpdateMarketCategory(ctx context.Context, in *UpdateMarketCategoryRequest, opts ...grpc.CallOption) (*UpdateMarketCategoryResponse, error)
	AddBusinessMarketCategory(ctx context.Context, in *AddBusinessMarketCategoryRequest, opts ...grpc.CallOption) (*AddBusinessMarketCategoryResponse, error)
	GetBusinessMarketCategories(ctx context.Context, in *GetBusinessMarketCategoriesRequest, opts ...grpc.CallOption) (*GetBusinessMarketCategoriesResponse, error)
	AddStore(ctx context.Context, in *AddStoreRequest, opts ...grpc.CallOption) (*AddStoreResponse, error)
	GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*GetStoreResponse, error)
	DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error)
	GetUnoccupiedStores(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetUnoccupiedStoresResponse, error)
	AddBranch(ctx context.Context, in *AddBranchRequest, opts ...grpc.CallOption) (*AddBranchResponse, error)
	GetBranch(ctx context.Context, in *GetBranchRequest, opts ...grpc.CallOption) (*GetBranchResponse, error)
	GetBusinessBranches(ctx context.Context, in *GetBusinessBranchesRequest, opts ...grpc.CallOption) (*GetBusinessBranchesResponse, error)
	UpdateBranch(ctx context.Context, in *UpdateBranchRequest, opts ...grpc.CallOption) (*UpdateBranchResponse, error)
	SuspendBranch(ctx context.Context, in *SuspendBranchRequest, opts ...grpc.CallOption) (*SuspendBranchResponse, error)
	ActivateBranch(ctx context.Context, in *ActivateBranchRequest, opts ...grpc.CallOption) (*ActivateBranchResponse, error)
	DeleteBranch(ctx context.Context, in *DeleteBranchRequest, opts ...grpc.CallOption) (*DeleteBranchResponse, error)
	AddStoreBranchRent(ctx context.Context, in *AddStoreBranchRentRequest, opts ...grpc.CallOption) (*AddStoreBranchRentResponse, error)
	GetStoreBranchRents(ctx context.Context, in *GetStoreBranchRentRequest, opts ...grpc.CallOption) (*GetStoreBranchRentResponse, error)
	UpdateStoreBranchRent(ctx context.Context, in *UpdateBranchRentRequest, opts ...grpc.CallOption) (*UpdateBranchRentResponse, error)
	GetUnpaidBranchRents(ctx context.Context, in *GetUnpaidBranchRentsRequest, opts ...grpc.CallOption) (*GetUnpaidBranchRentsResponse, error)
	GetBusinessUnpaidBranchRents(ctx context.Context, in *GetBusinessUnpaidBranchRentsRequest, opts ...grpc.CallOption) (*GetBusinessUnpaidBranchRentsResponse, error)
	AddProductCategory(ctx context.Context, in *AddProductCategoryRequest, opts ...grpc.CallOption) (*AddProductCategoryResponse, error)
	GetProductCategory(ctx context.Context, in *GetProductCategoryRequest, opts ...grpc.CallOption) (*GetProductCategoryResponse, error)
	UpdateProductCategory(ctx context.Context, in *UpdateProductCategoryRequest, opts ...grpc.CallOption) (*UpdateProductCategoryResponse, error)
	AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error)
	SuspendProduct(ctx context.Context, in *SuspendProductRequest, opts ...grpc.CallOption) (*SuspendProductResponse, error)
	ActivateProduct(ctx context.Context, in *ActivateProductRequest, opts ...grpc.CallOption) (*ActivateProductResponse, error)
	AddBusinessProduct(ctx context.Context, in *AddBusinessProductRequest, opts ...grpc.CallOption) (*AddBusinessProductResponse, error)
	GetBusinessProduct(ctx context.Context, in *GetBusinessProductRequest, opts ...grpc.CallOption) (*GetBusinessProductResponse, error)
	UpdateBusinessProduct(ctx context.Context, in *UpdateBusinessProductRequest, opts ...grpc.CallOption) (*UpdateBusinessProductResponse, error)
	SearchBusinessProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error)
	SuspendBusinessProduct(ctx context.Context, in *SuspendBusinessProductRequest, opts ...grpc.CallOption) (*SuspendBusinessProductResponse, error)
	ActivateBusinessProduct(ctx context.Context, in *ActivateBusinessProductRequest, opts ...grpc.CallOption) (*ActivateBusinessProductResponse, error)
	AddBranchProduct(ctx context.Context, in *AddBranchProductRequest, opts ...grpc.CallOption) (*AddBranchProductResponse, error)
	GetBranchProduct(ctx context.Context, in *GetBranchProductRequest, opts ...grpc.CallOption) (*GetBranchProductResponse, error)
	SearchBranchProducts(ctx context.Context, in *SearchBranchProductsRequest, opts ...grpc.CallOption) (*SearchBranchProductsResponse, error)
	UpdateBranchProduct(ctx context.Context, in *UpdateBranchProductRequest, opts ...grpc.CallOption) (*UpdateBranchProductResponse, error)
}

type businessClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessClient(cc grpc.ClientConnInterface) BusinessClient {
	return &businessClient{cc}
}

func (c *businessClient) AddBusiness(ctx context.Context, in *AddBusinessRequest, opts ...grpc.CallOption) (*AddBusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBusinessResponse)
	err := c.cc.Invoke(ctx, Business_AddBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetBusiness(ctx context.Context, in *GetBusinessRequest, opts ...grpc.CallOption) (*GetBusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusinessResponse)
	err := c.cc.Invoke(ctx, Business_GetBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) UpdateBusiness(ctx context.Context, in *UpdateBusinessRequest, opts ...grpc.CallOption) (*UpdateBusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBusinessResponse)
	err := c.cc.Invoke(ctx, Business_UpdateBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) SetBusinessProfilePicture(ctx context.Context, in *SetBusinessProfilePictureRequest, opts ...grpc.CallOption) (*SetBusinessProfilePictureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBusinessProfilePictureResponse)
	err := c.cc.Invoke(ctx, Business_SetBusinessProfilePicture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) SuspendBusiness(ctx context.Context, in *SuspendBusinessRequest, opts ...grpc.CallOption) (*SuspendBusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendBusinessResponse)
	err := c.cc.Invoke(ctx, Business_SuspendBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) ActivateBusiness(ctx context.Context, in *ActivateBusinessRequest, opts ...grpc.CallOption) (*ActivateBusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateBusinessResponse)
	err := c.cc.Invoke(ctx, Business_ActivateBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) DeleteBusiness(ctx context.Context, in *DeleteBusinessRequest, opts ...grpc.CallOption) (*DeleteBusinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBusinessResponse)
	err := c.cc.Invoke(ctx, Business_DeleteBusiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddBusinessOwner(ctx context.Context, in *AddBusinessOwnerRequest, opts ...grpc.CallOption) (*AddBusinessOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBusinessOwnerResponse)
	err := c.cc.Invoke(ctx, Business_AddBusinessOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) RemoveBusinessOwner(ctx context.Context, in *RemoveBusinessOwnerRequest, opts ...grpc.CallOption) (*RemoveBusinessOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBusinessOwnerResponse)
	err := c.cc.Invoke(ctx, Business_RemoveBusinessOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetBusinessOwners(ctx context.Context, in *GetBusinessOwnersRequest, opts ...grpc.CallOption) (*GetBusinessOwnersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusinessOwnersResponse)
	err := c.cc.Invoke(ctx, Business_GetBusinessOwners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddBusinessClient(ctx context.Context, in *AddBusinessClientRequest, opts ...grpc.CallOption) (*AddBusinessClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBusinessClientResponse)
	err := c.cc.Invoke(ctx, Business_AddBusinessClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) IsBusinessClient(ctx context.Context, in *IsBusinessClientRequest, opts ...grpc.CallOption) (*IsBusinessClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsBusinessClientResponse)
	err := c.cc.Invoke(ctx, Business_IsBusinessClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddMarketCategory(ctx context.Context, in *AddMarketCategoryRequest, opts ...grpc.CallOption) (*AddMarketCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMarketCategoryResponse)
	err := c.cc.Invoke(ctx, Business_AddMarketCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetMarketCategory(ctx context.Context, in *GetMarketCategoryRequest, opts ...grpc.CallOption) (*GetMarketCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketCategoryResponse)
	err := c.cc.Invoke(ctx, Business_GetMarketCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) UpdateMarketCategory(ctx context.Context, in *UpdateMarketCategoryRequest, opts ...grpc.CallOption) (*UpdateMarketCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMarketCategoryResponse)
	err := c.cc.Invoke(ctx, Business_UpdateMarketCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddBusinessMarketCategory(ctx context.Context, in *AddBusinessMarketCategoryRequest, opts ...grpc.CallOption) (*AddBusinessMarketCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBusinessMarketCategoryResponse)
	err := c.cc.Invoke(ctx, Business_AddBusinessMarketCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetBusinessMarketCategories(ctx context.Context, in *GetBusinessMarketCategoriesRequest, opts ...grpc.CallOption) (*GetBusinessMarketCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusinessMarketCategoriesResponse)
	err := c.cc.Invoke(ctx, Business_GetBusinessMarketCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddStore(ctx context.Context, in *AddStoreRequest, opts ...grpc.CallOption) (*AddStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddStoreResponse)
	err := c.cc.Invoke(ctx, Business_AddStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*GetStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoreResponse)
	err := c.cc.Invoke(ctx, Business_GetStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStoreResponse)
	err := c.cc.Invoke(ctx, Business_DeleteStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetUnoccupiedStores(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetUnoccupiedStoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnoccupiedStoresResponse)
	err := c.cc.Invoke(ctx, Business_GetUnoccupiedStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddBranch(ctx context.Context, in *AddBranchRequest, opts ...grpc.CallOption) (*AddBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBranchResponse)
	err := c.cc.Invoke(ctx, Business_AddBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetBranch(ctx context.Context, in *GetBranchRequest, opts ...grpc.CallOption) (*GetBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBranchResponse)
	err := c.cc.Invoke(ctx, Business_GetBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetBusinessBranches(ctx context.Context, in *GetBusinessBranchesRequest, opts ...grpc.CallOption) (*GetBusinessBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusinessBranchesResponse)
	err := c.cc.Invoke(ctx, Business_GetBusinessBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) UpdateBranch(ctx context.Context, in *UpdateBranchRequest, opts ...grpc.CallOption) (*UpdateBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBranchResponse)
	err := c.cc.Invoke(ctx, Business_UpdateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) SuspendBranch(ctx context.Context, in *SuspendBranchRequest, opts ...grpc.CallOption) (*SuspendBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendBranchResponse)
	err := c.cc.Invoke(ctx, Business_SuspendBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) ActivateBranch(ctx context.Context, in *ActivateBranchRequest, opts ...grpc.CallOption) (*ActivateBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateBranchResponse)
	err := c.cc.Invoke(ctx, Business_ActivateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) DeleteBranch(ctx context.Context, in *DeleteBranchRequest, opts ...grpc.CallOption) (*DeleteBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBranchResponse)
	err := c.cc.Invoke(ctx, Business_DeleteBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddStoreBranchRent(ctx context.Context, in *AddStoreBranchRentRequest, opts ...grpc.CallOption) (*AddStoreBranchRentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddStoreBranchRentResponse)
	err := c.cc.Invoke(ctx, Business_AddStoreBranchRent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetStoreBranchRents(ctx context.Context, in *GetStoreBranchRentRequest, opts ...grpc.CallOption) (*GetStoreBranchRentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoreBranchRentResponse)
	err := c.cc.Invoke(ctx, Business_GetStoreBranchRents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) UpdateStoreBranchRent(ctx context.Context, in *UpdateBranchRentRequest, opts ...grpc.CallOption) (*UpdateBranchRentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBranchRentResponse)
	err := c.cc.Invoke(ctx, Business_UpdateStoreBranchRent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetUnpaidBranchRents(ctx context.Context, in *GetUnpaidBranchRentsRequest, opts ...grpc.CallOption) (*GetUnpaidBranchRentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnpaidBranchRentsResponse)
	err := c.cc.Invoke(ctx, Business_GetUnpaidBranchRents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetBusinessUnpaidBranchRents(ctx context.Context, in *GetBusinessUnpaidBranchRentsRequest, opts ...grpc.CallOption) (*GetBusinessUnpaidBranchRentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusinessUnpaidBranchRentsResponse)
	err := c.cc.Invoke(ctx, Business_GetBusinessUnpaidBranchRents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddProductCategory(ctx context.Context, in *AddProductCategoryRequest, opts ...grpc.CallOption) (*AddProductCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProductCategoryResponse)
	err := c.cc.Invoke(ctx, Business_AddProductCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetProductCategory(ctx context.Context, in *GetProductCategoryRequest, opts ...grpc.CallOption) (*GetProductCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductCategoryResponse)
	err := c.cc.Invoke(ctx, Business_GetProductCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) UpdateProductCategory(ctx context.Context, in *UpdateProductCategoryRequest, opts ...grpc.CallOption) (*UpdateProductCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductCategoryResponse)
	err := c.cc.Invoke(ctx, Business_UpdateProductCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, Business_AddProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, Business_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, Business_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResponse)
	err := c.cc.Invoke(ctx, Business_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) SuspendProduct(ctx context.Context, in *SuspendProductRequest, opts ...grpc.CallOption) (*SuspendProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendProductResponse)
	err := c.cc.Invoke(ctx, Business_SuspendProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) ActivateProduct(ctx context.Context, in *ActivateProductRequest, opts ...grpc.CallOption) (*ActivateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateProductResponse)
	err := c.cc.Invoke(ctx, Business_ActivateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddBusinessProduct(ctx context.Context, in *AddBusinessProductRequest, opts ...grpc.CallOption) (*AddBusinessProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBusinessProductResponse)
	err := c.cc.Invoke(ctx, Business_AddBusinessProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetBusinessProduct(ctx context.Context, in *GetBusinessProductRequest, opts ...grpc.CallOption) (*GetBusinessProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusinessProductResponse)
	err := c.cc.Invoke(ctx, Business_GetBusinessProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) UpdateBusinessProduct(ctx context.Context, in *UpdateBusinessProductRequest, opts ...grpc.CallOption) (*UpdateBusinessProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBusinessProductResponse)
	err := c.cc.Invoke(ctx, Business_UpdateBusinessProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) SearchBusinessProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResponse)
	err := c.cc.Invoke(ctx, Business_SearchBusinessProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) SuspendBusinessProduct(ctx context.Context, in *SuspendBusinessProductRequest, opts ...grpc.CallOption) (*SuspendBusinessProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendBusinessProductResponse)
	err := c.cc.Invoke(ctx, Business_SuspendBusinessProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) ActivateBusinessProduct(ctx context.Context, in *ActivateBusinessProductRequest, opts ...grpc.CallOption) (*ActivateBusinessProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateBusinessProductResponse)
	err := c.cc.Invoke(ctx, Business_ActivateBusinessProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) AddBranchProduct(ctx context.Context, in *AddBranchProductRequest, opts ...grpc.CallOption) (*AddBranchProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBranchProductResponse)
	err := c.cc.Invoke(ctx, Business_AddBranchProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) GetBranchProduct(ctx context.Context, in *GetBranchProductRequest, opts ...grpc.CallOption) (*GetBranchProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBranchProductResponse)
	err := c.cc.Invoke(ctx, Business_GetBranchProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) SearchBranchProducts(ctx context.Context, in *SearchBranchProductsRequest, opts ...grpc.CallOption) (*SearchBranchProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchBranchProductsResponse)
	err := c.cc.Invoke(ctx, Business_SearchBranchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessClient) UpdateBranchProduct(ctx context.Context, in *UpdateBranchProductRequest, opts ...grpc.CallOption) (*UpdateBranchProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBranchProductResponse)
	err := c.cc.Invoke(ctx, Business_UpdateBranchProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessServer is the server API for Business service.
// All implementations must embed UnimplementedBusinessServer
// for forward compatibility.
type BusinessServer interface {
	AddBusiness(context.Context, *AddBusinessRequest) (*AddBusinessResponse, error)
	GetBusiness(context.Context, *GetBusinessRequest) (*GetBusinessResponse, error)
	UpdateBusiness(context.Context, *UpdateBusinessRequest) (*UpdateBusinessResponse, error)
	SetBusinessProfilePicture(context.Context, *SetBusinessProfilePictureRequest) (*SetBusinessProfilePictureResponse, error)
	SuspendBusiness(context.Context, *SuspendBusinessRequest) (*SuspendBusinessResponse, error)
	ActivateBusiness(context.Context, *ActivateBusinessRequest) (*ActivateBusinessResponse, error)
	DeleteBusiness(context.Context, *DeleteBusinessRequest) (*DeleteBusinessResponse, error)
	AddBusinessOwner(context.Context, *AddBusinessOwnerRequest) (*AddBusinessOwnerResponse, error)
	RemoveBusinessOwner(context.Context, *RemoveBusinessOwnerRequest) (*RemoveBusinessOwnerResponse, error)
	GetBusinessOwners(context.Context, *GetBusinessOwnersRequest) (*GetBusinessOwnersResponse, error)
	AddBusinessClient(context.Context, *AddBusinessClientRequest) (*AddBusinessClientResponse, error)
	IsBusinessClient(context.Context, *IsBusinessClientRequest) (*IsBusinessClientResponse, error)
	AddMarketCategory(context.Context, *AddMarketCategoryRequest) (*AddMarketCategoryResponse, error)
	GetMarketCategory(context.Context, *GetMarketCategoryRequest) (*GetMarketCategoryResponse, error)
	UpdateMarketCategory(context.Context, *UpdateMarketCategoryRequest) (*UpdateMarketCategoryResponse, error)
	AddBusinessMarketCategory(context.Context, *AddBusinessMarketCategoryRequest) (*AddBusinessMarketCategoryResponse, error)
	GetBusinessMarketCategories(context.Context, *GetBusinessMarketCategoriesRequest) (*GetBusinessMarketCategoriesResponse, error)
	AddStore(context.Context, *AddStoreRequest) (*AddStoreResponse, error)
	GetStore(context.Context, *GetStoreRequest) (*GetStoreResponse, error)
	DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error)
	GetUnoccupiedStores(context.Context, *emptypb.Empty) (*GetUnoccupiedStoresResponse, error)
	AddBranch(context.Context, *AddBranchRequest) (*AddBranchResponse, error)
	GetBranch(context.Context, *GetBranchRequest) (*GetBranchResponse, error)
	GetBusinessBranches(context.Context, *GetBusinessBranchesRequest) (*GetBusinessBranchesResponse, error)
	UpdateBranch(context.Context, *UpdateBranchRequest) (*UpdateBranchResponse, error)
	SuspendBranch(context.Context, *SuspendBranchRequest) (*SuspendBranchResponse, error)
	ActivateBranch(context.Context, *ActivateBranchRequest) (*ActivateBranchResponse, error)
	DeleteBranch(context.Context, *DeleteBranchRequest) (*DeleteBranchResponse, error)
	AddStoreBranchRent(context.Context, *AddStoreBranchRentRequest) (*AddStoreBranchRentResponse, error)
	GetStoreBranchRents(context.Context, *GetStoreBranchRentRequest) (*GetStoreBranchRentResponse, error)
	UpdateStoreBranchRent(context.Context, *UpdateBranchRentRequest) (*UpdateBranchRentResponse, error)
	GetUnpaidBranchRents(context.Context, *GetUnpaidBranchRentsRequest) (*GetUnpaidBranchRentsResponse, error)
	GetBusinessUnpaidBranchRents(context.Context, *GetBusinessUnpaidBranchRentsRequest) (*GetBusinessUnpaidBranchRentsResponse, error)
	AddProductCategory(context.Context, *AddProductCategoryRequest) (*AddProductCategoryResponse, error)
	GetProductCategory(context.Context, *GetProductCategoryRequest) (*GetProductCategoryResponse, error)
	UpdateProductCategory(context.Context, *UpdateProductCategoryRequest) (*UpdateProductCategoryResponse, error)
	AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error)
	SuspendProduct(context.Context, *SuspendProductRequest) (*SuspendProductResponse, error)
	ActivateProduct(context.Context, *ActivateProductRequest) (*ActivateProductResponse, error)
	AddBusinessProduct(context.Context, *AddBusinessProductRequest) (*AddBusinessProductResponse, error)
	GetBusinessProduct(context.Context, *GetBusinessProductRequest) (*GetBusinessProductResponse, error)
	UpdateBusinessProduct(context.Context, *UpdateBusinessProductRequest) (*UpdateBusinessProductResponse, error)
	SearchBusinessProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error)
	SuspendBusinessProduct(context.Context, *SuspendBusinessProductRequest) (*SuspendBusinessProductResponse, error)
	ActivateBusinessProduct(context.Context, *ActivateBusinessProductRequest) (*ActivateBusinessProductResponse, error)
	AddBranchProduct(context.Context, *AddBranchProductRequest) (*AddBranchProductResponse, error)
	GetBranchProduct(context.Context, *GetBranchProductRequest) (*GetBranchProductResponse, error)
	SearchBranchProducts(context.Context, *SearchBranchProductsRequest) (*SearchBranchProductsResponse, error)
	UpdateBranchProduct(context.Context, *UpdateBranchProductRequest) (*UpdateBranchProductResponse, error)
	mustEmbedUnimplementedBusinessServer()
}

// UnimplementedBusinessServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBusinessServer struct{}

func (UnimplementedBusinessServer) AddBusiness(context.Context, *AddBusinessRequest) (*AddBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBusiness not implemented")
}
func (UnimplementedBusinessServer) GetBusiness(context.Context, *GetBusinessRequest) (*GetBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusiness not implemented")
}
func (UnimplementedBusinessServer) UpdateBusiness(context.Context, *UpdateBusinessRequest) (*UpdateBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBusiness not implemented")
}
func (UnimplementedBusinessServer) SetBusinessProfilePicture(context.Context, *SetBusinessProfilePictureRequest) (*SetBusinessProfilePictureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBusinessProfilePicture not implemented")
}
func (UnimplementedBusinessServer) SuspendBusiness(context.Context, *SuspendBusinessRequest) (*SuspendBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendBusiness not implemented")
}
func (UnimplementedBusinessServer) ActivateBusiness(context.Context, *ActivateBusinessRequest) (*ActivateBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateBusiness not implemented")
}
func (UnimplementedBusinessServer) DeleteBusiness(context.Context, *DeleteBusinessRequest) (*DeleteBusinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBusiness not implemented")
}
func (UnimplementedBusinessServer) AddBusinessOwner(context.Context, *AddBusinessOwnerRequest) (*AddBusinessOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBusinessOwner not implemented")
}
func (UnimplementedBusinessServer) RemoveBusinessOwner(context.Context, *RemoveBusinessOwnerRequest) (*RemoveBusinessOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBusinessOwner not implemented")
}
func (UnimplementedBusinessServer) GetBusinessOwners(context.Context, *GetBusinessOwnersRequest) (*GetBusinessOwnersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessOwners not implemented")
}
func (UnimplementedBusinessServer) AddBusinessClient(context.Context, *AddBusinessClientRequest) (*AddBusinessClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBusinessClient not implemented")
}
func (UnimplementedBusinessServer) IsBusinessClient(context.Context, *IsBusinessClientRequest) (*IsBusinessClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsBusinessClient not implemented")
}
func (UnimplementedBusinessServer) AddMarketCategory(context.Context, *AddMarketCategoryRequest) (*AddMarketCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMarketCategory not implemented")
}
func (UnimplementedBusinessServer) GetMarketCategory(context.Context, *GetMarketCategoryRequest) (*GetMarketCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketCategory not implemented")
}
func (UnimplementedBusinessServer) UpdateMarketCategory(context.Context, *UpdateMarketCategoryRequest) (*UpdateMarketCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMarketCategory not implemented")
}
func (UnimplementedBusinessServer) AddBusinessMarketCategory(context.Context, *AddBusinessMarketCategoryRequest) (*AddBusinessMarketCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBusinessMarketCategory not implemented")
}
func (UnimplementedBusinessServer) GetBusinessMarketCategories(context.Context, *GetBusinessMarketCategoriesRequest) (*GetBusinessMarketCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessMarketCategories not implemented")
}
func (UnimplementedBusinessServer) AddStore(context.Context, *AddStoreRequest) (*AddStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStore not implemented")
}
func (UnimplementedBusinessServer) GetStore(context.Context, *GetStoreRequest) (*GetStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStore not implemented")
}
func (UnimplementedBusinessServer) DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStore not implemented")
}
func (UnimplementedBusinessServer) GetUnoccupiedStores(context.Context, *emptypb.Empty) (*GetUnoccupiedStoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnoccupiedStores not implemented")
}
func (UnimplementedBusinessServer) AddBranch(context.Context, *AddBranchRequest) (*AddBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBranch not implemented")
}
func (UnimplementedBusinessServer) GetBranch(context.Context, *GetBranchRequest) (*GetBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBranch not implemented")
}
func (UnimplementedBusinessServer) GetBusinessBranches(context.Context, *GetBusinessBranchesRequest) (*GetBusinessBranchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessBranches not implemented")
}
func (UnimplementedBusinessServer) UpdateBranch(context.Context, *UpdateBranchRequest) (*UpdateBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBranch not implemented")
}
func (UnimplementedBusinessServer) SuspendBranch(context.Context, *SuspendBranchRequest) (*SuspendBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendBranch not implemented")
}
func (UnimplementedBusinessServer) ActivateBranch(context.Context, *ActivateBranchRequest) (*ActivateBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateBranch not implemented")
}
func (UnimplementedBusinessServer) DeleteBranch(context.Context, *DeleteBranchRequest) (*DeleteBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBranch not implemented")
}
func (UnimplementedBusinessServer) AddStoreBranchRent(context.Context, *AddStoreBranchRentRequest) (*AddStoreBranchRentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStoreBranchRent not implemented")
}
func (UnimplementedBusinessServer) GetStoreBranchRents(context.Context, *GetStoreBranchRentRequest) (*GetStoreBranchRentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStoreBranchRents not implemented")
}
func (UnimplementedBusinessServer) UpdateStoreBranchRent(context.Context, *UpdateBranchRentRequest) (*UpdateBranchRentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStoreBranchRent not implemented")
}
func (UnimplementedBusinessServer) GetUnpaidBranchRents(context.Context, *GetUnpaidBranchRentsRequest) (*GetUnpaidBranchRentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnpaidBranchRents not implemented")
}
func (UnimplementedBusinessServer) GetBusinessUnpaidBranchRents(context.Context, *GetBusinessUnpaidBranchRentsRequest) (*GetBusinessUnpaidBranchRentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessUnpaidBranchRents not implemented")
}
func (UnimplementedBusinessServer) AddProductCategory(context.Context, *AddProductCategoryRequest) (*AddProductCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProductCategory not implemented")
}
func (UnimplementedBusinessServer) GetProductCategory(context.Context, *GetProductCategoryRequest) (*GetProductCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductCategory not implemented")
}
func (UnimplementedBusinessServer) UpdateProductCategory(context.Context, *UpdateProductCategoryRequest) (*UpdateProductCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductCategory not implemented")
}
func (UnimplementedBusinessServer) AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (UnimplementedBusinessServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedBusinessServer) UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedBusinessServer) SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedBusinessServer) SuspendProduct(context.Context, *SuspendProductRequest) (*SuspendProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendProduct not implemented")
}
func (UnimplementedBusinessServer) ActivateProduct(context.Context, *ActivateProductRequest) (*ActivateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateProduct not implemented")
}
func (UnimplementedBusinessServer) AddBusinessProduct(context.Context, *AddBusinessProductRequest) (*AddBusinessProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBusinessProduct not implemented")
}
func (UnimplementedBusinessServer) GetBusinessProduct(context.Context, *GetBusinessProductRequest) (*GetBusinessProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessProduct not implemented")
}
func (UnimplementedBusinessServer) UpdateBusinessProduct(context.Context, *UpdateBusinessProductRequest) (*UpdateBusinessProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBusinessProduct not implemented")
}
func (UnimplementedBusinessServer) SearchBusinessProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBusinessProducts not implemented")
}
func (UnimplementedBusinessServer) SuspendBusinessProduct(context.Context, *SuspendBusinessProductRequest) (*SuspendBusinessProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendBusinessProduct not implemented")
}
func (UnimplementedBusinessServer) ActivateBusinessProduct(context.Context, *ActivateBusinessProductRequest) (*ActivateBusinessProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateBusinessProduct not implemented")
}
func (UnimplementedBusinessServer) AddBranchProduct(context.Context, *AddBranchProductRequest) (*AddBranchProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBranchProduct not implemented")
}
func (UnimplementedBusinessServer) GetBranchProduct(context.Context, *GetBranchProductRequest) (*GetBranchProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBranchProduct not implemented")
}
func (UnimplementedBusinessServer) SearchBranchProducts(context.Context, *SearchBranchProductsRequest) (*SearchBranchProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBranchProducts not implemented")
}
func (UnimplementedBusinessServer) UpdateBranchProduct(context.Context, *UpdateBranchProductRequest) (*UpdateBranchProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBranchProduct not implemented")
}
func (UnimplementedBusinessServer) mustEmbedUnimplementedBusinessServer() {}
func (UnimplementedBusinessServer) testEmbeddedByValue()                  {}

// UnsafeBusinessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BusinessServer will
// result in compilation errors.
type UnsafeBusinessServer interface {
	mustEmbedUnimplementedBusinessServer()
}

func RegisterBusinessServer(s grpc.ServiceRegistrar, srv BusinessServer) {
	// If the following call pancis, it indicates UnimplementedBusinessServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Business_ServiceDesc, srv)
}

func _Business_AddBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddBusiness(ctx, req.(*AddBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetBusiness(ctx, req.(*GetBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_UpdateBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).UpdateBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_UpdateBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).UpdateBusiness(ctx, req.(*UpdateBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_SetBusinessProfilePicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBusinessProfilePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).SetBusinessProfilePicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_SetBusinessProfilePicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).SetBusinessProfilePicture(ctx, req.(*SetBusinessProfilePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_SuspendBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).SuspendBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_SuspendBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).SuspendBusiness(ctx, req.(*SuspendBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_ActivateBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).ActivateBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_ActivateBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).ActivateBusiness(ctx, req.(*ActivateBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_DeleteBusiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).DeleteBusiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_DeleteBusiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).DeleteBusiness(ctx, req.(*DeleteBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddBusinessOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBusinessOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddBusinessOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddBusinessOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddBusinessOwner(ctx, req.(*AddBusinessOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_RemoveBusinessOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBusinessOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).RemoveBusinessOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_RemoveBusinessOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).RemoveBusinessOwner(ctx, req.(*RemoveBusinessOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetBusinessOwners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessOwnersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetBusinessOwners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetBusinessOwners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetBusinessOwners(ctx, req.(*GetBusinessOwnersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddBusinessClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBusinessClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddBusinessClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddBusinessClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddBusinessClient(ctx, req.(*AddBusinessClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_IsBusinessClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsBusinessClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).IsBusinessClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_IsBusinessClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).IsBusinessClient(ctx, req.(*IsBusinessClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddMarketCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMarketCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddMarketCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddMarketCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddMarketCategory(ctx, req.(*AddMarketCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetMarketCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetMarketCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetMarketCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetMarketCategory(ctx, req.(*GetMarketCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_UpdateMarketCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMarketCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).UpdateMarketCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_UpdateMarketCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).UpdateMarketCategory(ctx, req.(*UpdateMarketCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddBusinessMarketCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBusinessMarketCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddBusinessMarketCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddBusinessMarketCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddBusinessMarketCategory(ctx, req.(*AddBusinessMarketCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetBusinessMarketCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessMarketCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetBusinessMarketCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetBusinessMarketCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetBusinessMarketCategories(ctx, req.(*GetBusinessMarketCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddStore(ctx, req.(*AddStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetStore(ctx, req.(*GetStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_DeleteStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).DeleteStore(ctx, req.(*DeleteStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetUnoccupiedStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetUnoccupiedStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetUnoccupiedStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetUnoccupiedStores(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddBranch(ctx, req.(*AddBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetBranch(ctx, req.(*GetBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetBusinessBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetBusinessBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetBusinessBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetBusinessBranches(ctx, req.(*GetBusinessBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_UpdateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).UpdateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_UpdateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).UpdateBranch(ctx, req.(*UpdateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_SuspendBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).SuspendBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_SuspendBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).SuspendBranch(ctx, req.(*SuspendBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_ActivateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).ActivateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_ActivateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).ActivateBranch(ctx, req.(*ActivateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_DeleteBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).DeleteBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_DeleteBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).DeleteBranch(ctx, req.(*DeleteBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddStoreBranchRent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStoreBranchRentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddStoreBranchRent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddStoreBranchRent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddStoreBranchRent(ctx, req.(*AddStoreBranchRentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetStoreBranchRents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreBranchRentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetStoreBranchRents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetStoreBranchRents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetStoreBranchRents(ctx, req.(*GetStoreBranchRentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_UpdateStoreBranchRent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBranchRentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).UpdateStoreBranchRent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_UpdateStoreBranchRent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).UpdateStoreBranchRent(ctx, req.(*UpdateBranchRentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetUnpaidBranchRents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnpaidBranchRentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetUnpaidBranchRents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetUnpaidBranchRents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetUnpaidBranchRents(ctx, req.(*GetUnpaidBranchRentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetBusinessUnpaidBranchRents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessUnpaidBranchRentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetBusinessUnpaidBranchRents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetBusinessUnpaidBranchRents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetBusinessUnpaidBranchRents(ctx, req.(*GetBusinessUnpaidBranchRentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddProductCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddProductCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddProductCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddProductCategory(ctx, req.(*AddProductCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetProductCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetProductCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetProductCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetProductCategory(ctx, req.(*GetProductCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_UpdateProductCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).UpdateProductCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_UpdateProductCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).UpdateProductCategory(ctx, req.(*UpdateProductCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).SearchProducts(ctx, req.(*SearchProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_SuspendProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).SuspendProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_SuspendProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).SuspendProduct(ctx, req.(*SuspendProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_ActivateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).ActivateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_ActivateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).ActivateProduct(ctx, req.(*ActivateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddBusinessProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBusinessProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddBusinessProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddBusinessProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddBusinessProduct(ctx, req.(*AddBusinessProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetBusinessProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetBusinessProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetBusinessProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetBusinessProduct(ctx, req.(*GetBusinessProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_UpdateBusinessProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBusinessProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).UpdateBusinessProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_UpdateBusinessProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).UpdateBusinessProduct(ctx, req.(*UpdateBusinessProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_SearchBusinessProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).SearchBusinessProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_SearchBusinessProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).SearchBusinessProducts(ctx, req.(*SearchProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_SuspendBusinessProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendBusinessProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).SuspendBusinessProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_SuspendBusinessProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).SuspendBusinessProduct(ctx, req.(*SuspendBusinessProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_ActivateBusinessProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateBusinessProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).ActivateBusinessProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_ActivateBusinessProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).ActivateBusinessProduct(ctx, req.(*ActivateBusinessProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_AddBranchProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBranchProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).AddBranchProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_AddBranchProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).AddBranchProduct(ctx, req.(*AddBranchProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_GetBranchProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBranchProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).GetBranchProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_GetBranchProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).GetBranchProduct(ctx, req.(*GetBranchProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_SearchBranchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBranchProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).SearchBranchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_SearchBranchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).SearchBranchProducts(ctx, req.(*SearchBranchProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Business_UpdateBranchProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBranchProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServer).UpdateBranchProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Business_UpdateBranchProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServer).UpdateBranchProduct(ctx, req.(*UpdateBranchProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Business_ServiceDesc is the grpc.ServiceDesc for Business service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Business_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pixel_plaza.Business",
	HandlerType: (*BusinessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBusiness",
			Handler:    _Business_AddBusiness_Handler,
		},
		{
			MethodName: "GetBusiness",
			Handler:    _Business_GetBusiness_Handler,
		},
		{
			MethodName: "UpdateBusiness",
			Handler:    _Business_UpdateBusiness_Handler,
		},
		{
			MethodName: "SetBusinessProfilePicture",
			Handler:    _Business_SetBusinessProfilePicture_Handler,
		},
		{
			MethodName: "SuspendBusiness",
			Handler:    _Business_SuspendBusiness_Handler,
		},
		{
			MethodName: "ActivateBusiness",
			Handler:    _Business_ActivateBusiness_Handler,
		},
		{
			MethodName: "DeleteBusiness",
			Handler:    _Business_DeleteBusiness_Handler,
		},
		{
			MethodName: "AddBusinessOwner",
			Handler:    _Business_AddBusinessOwner_Handler,
		},
		{
			MethodName: "RemoveBusinessOwner",
			Handler:    _Business_RemoveBusinessOwner_Handler,
		},
		{
			MethodName: "GetBusinessOwners",
			Handler:    _Business_GetBusinessOwners_Handler,
		},
		{
			MethodName: "AddBusinessClient",
			Handler:    _Business_AddBusinessClient_Handler,
		},
		{
			MethodName: "IsBusinessClient",
			Handler:    _Business_IsBusinessClient_Handler,
		},
		{
			MethodName: "AddMarketCategory",
			Handler:    _Business_AddMarketCategory_Handler,
		},
		{
			MethodName: "GetMarketCategory",
			Handler:    _Business_GetMarketCategory_Handler,
		},
		{
			MethodName: "UpdateMarketCategory",
			Handler:    _Business_UpdateMarketCategory_Handler,
		},
		{
			MethodName: "AddBusinessMarketCategory",
			Handler:    _Business_AddBusinessMarketCategory_Handler,
		},
		{
			MethodName: "GetBusinessMarketCategories",
			Handler:    _Business_GetBusinessMarketCategories_Handler,
		},
		{
			MethodName: "AddStore",
			Handler:    _Business_AddStore_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _Business_GetStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _Business_DeleteStore_Handler,
		},
		{
			MethodName: "GetUnoccupiedStores",
			Handler:    _Business_GetUnoccupiedStores_Handler,
		},
		{
			MethodName: "AddBranch",
			Handler:    _Business_AddBranch_Handler,
		},
		{
			MethodName: "GetBranch",
			Handler:    _Business_GetBranch_Handler,
		},
		{
			MethodName: "GetBusinessBranches",
			Handler:    _Business_GetBusinessBranches_Handler,
		},
		{
			MethodName: "UpdateBranch",
			Handler:    _Business_UpdateBranch_Handler,
		},
		{
			MethodName: "SuspendBranch",
			Handler:    _Business_SuspendBranch_Handler,
		},
		{
			MethodName: "ActivateBranch",
			Handler:    _Business_ActivateBranch_Handler,
		},
		{
			MethodName: "DeleteBranch",
			Handler:    _Business_DeleteBranch_Handler,
		},
		{
			MethodName: "AddStoreBranchRent",
			Handler:    _Business_AddStoreBranchRent_Handler,
		},
		{
			MethodName: "GetStoreBranchRents",
			Handler:    _Business_GetStoreBranchRents_Handler,
		},
		{
			MethodName: "UpdateStoreBranchRent",
			Handler:    _Business_UpdateStoreBranchRent_Handler,
		},
		{
			MethodName: "GetUnpaidBranchRents",
			Handler:    _Business_GetUnpaidBranchRents_Handler,
		},
		{
			MethodName: "GetBusinessUnpaidBranchRents",
			Handler:    _Business_GetBusinessUnpaidBranchRents_Handler,
		},
		{
			MethodName: "AddProductCategory",
			Handler:    _Business_AddProductCategory_Handler,
		},
		{
			MethodName: "GetProductCategory",
			Handler:    _Business_GetProductCategory_Handler,
		},
		{
			MethodName: "UpdateProductCategory",
			Handler:    _Business_UpdateProductCategory_Handler,
		},
		{
			MethodName: "AddProduct",
			Handler:    _Business_AddProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _Business_GetProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _Business_UpdateProduct_Handler,
		},
		{
			MethodName: "SearchProducts",
			Handler:    _Business_SearchProducts_Handler,
		},
		{
			MethodName: "SuspendProduct",
			Handler:    _Business_SuspendProduct_Handler,
		},
		{
			MethodName: "ActivateProduct",
			Handler:    _Business_ActivateProduct_Handler,
		},
		{
			MethodName: "AddBusinessProduct",
			Handler:    _Business_AddBusinessProduct_Handler,
		},
		{
			MethodName: "GetBusinessProduct",
			Handler:    _Business_GetBusinessProduct_Handler,
		},
		{
			MethodName: "UpdateBusinessProduct",
			Handler:    _Business_UpdateBusinessProduct_Handler,
		},
		{
			MethodName: "SearchBusinessProducts",
			Handler:    _Business_SearchBusinessProducts_Handler,
		},
		{
			MethodName: "SuspendBusinessProduct",
			Handler:    _Business_SuspendBusinessProduct_Handler,
		},
		{
			MethodName: "ActivateBusinessProduct",
			Handler:    _Business_ActivateBusinessProduct_Handler,
		},
		{
			MethodName: "AddBranchProduct",
			Handler:    _Business_AddBranchProduct_Handler,
		},
		{
			MethodName: "GetBranchProduct",
			Handler:    _Business_GetBranchProduct_Handler,
		},
		{
			MethodName: "SearchBranchProducts",
			Handler:    _Business_SearchBranchProducts_Handler,
		},
		{
			MethodName: "UpdateBranchProduct",
			Handler:    _Business_UpdateBranchProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pixel_plaza/business.proto",
}
